#!/usr/bin/env ruby

require "erb"
require "json"

def collapse_newlines(s)
  s.gsub(/\n+/, "\n").gsub(/\A\s+|\s+\Z/, "")
end

TEMPLATE = <<END
// ==UserScript==
<%= config.map { |c| "// " + c }.join("\n") %>
// ==/UserScript==
(function() {
  var css = <%= JSON.dump(css) %>;
  if (typeof GM_addStyle != "undefined") {
    GM_addStyle(css);
  } else if (typeof PRO_addStyle != "undefined") {
    PRO_addStyle(css);
  } else if (typeof addStyle != "undefined") {
    addStyle(css);
  } else {
    var heads = document.getElementsByTagName("head");
    if (heads.length > 0) {
      var node = document.createElement("style");
      node.type = "text/css";
      node.appendChild(document.createTextNode(css));
      heads[0].appendChild(node); 
    }
  }
})();
END

ARGV.each do |src|
  dest = src.sub(/\.css$|$/, ".user.js")

  css = File.read(src)

  comments = []
  css.gsub!(/\/\*(.*?)\*\//m){ $1
    comments << $1
    ""
  }

  config = comments.join("\n").scan(/^@.*/)

  js = ERB.new(TEMPLATE).result(binding)

  File.open(dest, "w") do |f|
    f.puts js
  end
end
